version: "2"
services:
  agent:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PORT=9091
    volumes:
      - ./:/home/node/app
    ports:
      - "9091:9091"
    command: "npm run agent"

