apiVersion: v1
kind: ConfigMap
metadata:
  name: gtm-agent-configmap
data:
  GTM_AWS_REGION: ap-southeast-2
  GTM_SQS_PENDING_QUEUE: gtmPendingQueue
  GTM_SQS_RESULTS_QUEUE: gtmResultsQueue
  GTM_SNS_RESULTS_TOPIC: gtmResultsSNSTopic
  GTM_AGENT_PORT: "9091"
  GTM_AGENT_AWS_ACCESS_KEY_ID: AKIAISVCG2GDNCIUKBUA
  GTM_AGENT_AWS_SECRET_ACCESS_KEY: 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

---
apiVersion: v1
kind: Pod
metadata:
  name: gtm-agent-pod
  labels:
    name: gtm-agent-pod
spec:
  containers:
    - name: gtm-agent
      image: wyvern8/github-task-manager
      envFrom:
        - configMapRef:
            name: gtm-agent-configmap
  restartPolicy: Never

---
kind: Service
apiVersion: v1
metadata:
  name: gtm-agent-service
spec:
  selector:
    name: gtm-agent-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9091
  type: LoadBalancer

---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: gtm-agent-ingress
#spec:
#  backend:
#    serviceName: gtm-agent-service
#    servicePort: 80

